@startuml
AAUOC o-- Location
AAUOC o-- Person
AAUOC o-- Event

Event <|--BoardMeeting

Event -- Location


Person  <|-- Member
Person -- Conference

Member <|-- BoardMember

Event -- Member
(BoardMeeting,Event) .Conference
BoardMeeting -- BoardMember

@enduml