@startuml
class AAUOC{
newLocation(l : Location) : void
newEvent(e : Event) : void
newPerson(p : Person) : void
informEvent(e : Event) : void
register(m : Member,e : Event) : void
}
class Person{
name : String
}
class Location{
description : String
address : String
}
class Event{
date : Date
description : String
assign(l : Location) : void
}
class Conference{
max_attendees : Integer
}
class Member{
e-mail : String
}

AAUOC o-- Location
AAUOC o-- Person
AAUOC o-- Event

Event <|--BoardMeeting

Event -- Location


Person  <|-- Member
Person -- Conference

Member <|-- BoardMember

Event -- Member
(BoardMeeting,Event) .Conference
BoardMeeting -- BoardMember

@enduml