@startuml


AAUOC o-- "0...*" Location
AAUOC o-- "0...*" Event
AAUOC o-- "0...*" Person

Event <|--BoardMeeting
Event "0...*" -- "1" Location : isLocatedIn
Event "0...*" -- "0...*" Member :attendsTo



Person  <|-- Member
Person "0...*" -- "0...*" Conference

Member <|-- BoardMember

BoardMeeting "0...*" -- "0...*" BoardMember : attendsTo
(BoardMeeting,Event) .Conference


@enduml